fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    staging: "https://github.com/nanliu/puppet-staging"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql"
  symlinks:
    nilesh_mysql_profile: "#{source_dir}"
